apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: smf-fill-and-spill-policy
spec:

  # this section prioritizes workload clusters in the order listed below
  orderedClusterSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [selvi-onprem, selvi-cloud]

  # this policy matches those resources that have this label' key value pair
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app: span-multiple

  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  groupBy:
    labelKey: app
