apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: policy-cs-resources
spec:
  spreadConstraints:
    spreadMode: Duplicate
    topologyKey: kubernetes.io/metadata.name

  # policy matches all resources with the following label
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app: smf-cs-resources
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  groupBy:
    labelKey: app
