apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: all-in-ns-labelled-policy
spec:

  # matches all resources in namespace ${SMF_NAMESPACE_1}
  namespaceSelector:
     matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - ${SMF_NAMESPACE_1}

  # matches all cluster-scoped resources with the following label
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/component: smf
  
  # alternatively this also matches all cluster-scoped resources with the following label
  # the list below can be extended to a list of labels to be matched.
  # If more than one element exists in the list, the presence of either of 
  # the labels is sufficient for a resource to be matched to this policy
  #resourceSelectors:
  #   matchExpressions:
  #    - key: app.kubernetes.io/component
  #      operator: In
  #      values:
  #        - smf


  # matches cluster with labels in the list
  clusterSelector:
    matchLabels:
      kubernetes.io/metadata.name: ${NOVA_WORKLOAD_CLUSTER_1}
  groupBy:
    labelKey: app.kubernetes.io/component

