apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: simple-policy
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/component: smf
  clusterSelector:
    matchLabels:
      kubernetes.io/metadata.name: ${NOVA_WORKLOAD_CLUSTER_1}
  groupBy:
    labelKey: app.kubernetes.io/component
